name: map_tester
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_map: ^0.5.6
  location: any
  dio: any
  flutter_map_marker_cluster: any
  camera: ^0.5.2+2

  geocoder: any

  geolocator: any
  image_picker: ^0.6.1

  flutter:
    sdk: flutter

  tuple: ^1.0.2
  latlong: ^0.6.1
  positioned_tap_detector: ^1.0.2
  transparent_image: ^1.0.0
  async: ^2.1.0
  # todo(johnpryan): use stable version
  # https://github.com/flutter/flutter_image/pull/15
  flutter_image: ^2.0.0-dev.1
  cached_network_image: ^1.0.0
  sqflite: ^1.1.5
  path_provider: ^1.1.0
flutter:
    uses-material-design: true

dev_dependencies:
  pedantic: ^1.5.0
  flutter_test:
    sdk: flutter
  test: ^1.6.1